import Head from "next/head";
import Header from "./components/layout/header";
import Hero from "./components/hero";
import Footer from "./components/layout/footer";
import Image from "next/image";
import styles from "../styles/General.module.css";
import Experience from "./components/experience";
import Projects from "./components/projects";
import Vlogs from "./components/vlogs";

export default function Home() {
  const headerEl = <Header />;
  const sectionHeroEl = <Hero />;

  return (
    <div className={styles.container}>
      <Head>
        <title>Danica Velarde</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />

        <script
          type="module"
          src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
        ></script>
        <script
          nomodule
          src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
        ></script>
      </Head>
      <Header />
      <main className={styles.main}>
        {sectionHeroEl}
        <Experience />
        <Projects />
        <Vlogs />
      </main>
      <Footer />
    </div>
  );
}
